db:
  url: jdbc:postgresql://localhost:5432/user_db1
  username: 'admin1234'
  password: 'admin1234'

spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


keycloak:
  server-url: http://localhost:8070
  realm: ""
  client-id: "auth-service"
  client-secret: ""
  jwt-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
